spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_DATABASE:demo-db}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: demo

server:
  port: ${APP_PORT:8082}
  address: 0.0.0.0